# 01 - Import & Exploration initiale

**Projet**: Prédiction du Churn Client Télécom

**Objectif** : charges le dataset, comprendre sa structure

Source des données : https://www.kaggle.com/datasets/blastchar/telco-customer-churn

In [1]:
# Import
import sys, os
sys.path.append(os.path.abspath('..'))
from src.cleaning import loadData

import pandas as pd
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max.rows', 10)

DATA_PATH = '../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'

## 1. Chargement

In [2]:
df_raw = pd.read_csv(DATA_PATH)
loadData()

Shape : (7043, 21) (7,043 lignes x 21 colonnes)

Colonne (21) :
   1. customerID (str)
   2. gender (str)
   3. SeniorCitizen (int64)
   4. Partner (str)
   5. Dependents (str)
   6. tenure (int64)
   7. PhoneService (str)
   8. MultipleLines (str)
   9. InternetService (str)
  10. OnlineSecurity (str)
  11. OnlineBackup (str)
  12. DeviceProtection (str)
  13. TechSupport (str)
  14. StreamingTV (str)
  15. StreamingMovies (str)
  16. Contract (str)
  17. PaperlessBilling (str)
  18. PaymentMethod (str)
  19. MonthlyCharges (float64)
  20. TotalCharges (str)
  21. Churn (str)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df_raw.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## 2. Diagnostics

#### Types & valeurs manquantes

In [4]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

#### Valeurs manquantes

In [7]:
missing = df_raw.isnull().sum()

if missing.sum() == 0:
    print('Aucune valeur NaN détectée')
else:
    print(missing[missing>0])

Aucune valeur NaN détectée

#### Colonnes catégorielles - valeurs uniques

In [ ]:
for col in df_raw.select_dtypes(include='object').columns:
    val = df_raw[col].unique().tolist()

  customerID                     (7043 val.) : ['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU', '9305-CDSKC']
  gender                         (2 val.) : ['Female', 'Male']
  Partner                        (2 val.) : ['Yes', 'No']
  Dependents                     (2 val.) : ['No', 'Yes']
  PhoneService                   (2 val.) : ['No', 'Yes']
  MultipleLines                  (3 val.) : ['No phone service', 'No', 'Yes']
  InternetService                (3 val.) : ['DSL', 'Fiber optic', 'No']
  OnlineSecurity                 (3 val.) : ['No', 'Yes', 'No internet service']
  OnlineBackup                   (3 val.) : ['Yes', 'No', 'No internet service']
  DeviceProtection               (3 val.) : ['No', 'Yes', 'No internet service']
  TechSupport                    (3 val.) : ['No', 'Yes', 'No internet service']
  StreamingTV                    (3 val.) : ['No', 'Yes', 'No internet service']
  StreamingMovies                (3 val.) : ['No', 'Yes', 'No internet service']
  Contract                       (3 val.) : ['Month-to-month', 'One year', 'Two year']
  PaperlessBilling               (2 val.) : ['Yes', 'No']
  PaymentMethod                  (4 val.) : ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']
  TotalCharges                   (6531 val.) : ['29.85', '1889.5', '108.15', '1840.75', '151.65', '820.5']
  Churn                          (2 val.) : ['No', 'Yes']